"""Non-mandatory label and form text patterns to exclude from field extraction."""

MARKETING_HINTS = (
    "batch no",
    "lot no",
    "qr code",
    "scan here",
    "www.",
    "http",
    "bottled by",
    "bottled at",
    "bottled in bond",
    "product of",
    "enjoy responsibly",
    "distilled in",
    "est.",
    "est ",
    "cocktail recipes",
    "warehouse",
    "dsp-",
    "bw-",
    "tpwbh-",
    "registry",
    "plant no",
    "ttb f 5100",
    "serial number",
    "rep. id",
    "department of the treasury",
    "alcohol and tobacco tax",
)
